name: Ubuntu-GCC-x64

on:
  push:
    branches:
      - devel
      - main
  pull_request:

jobs:
  test_execution:
    runs-on: ubuntu-latest
    env:
      CC: gcc
      CXX: g++
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          cmake --preset=ci-ubuntu-gcc
          cmake --build build
      - name: test
        run: |
          cd build
          GTEST_OUTPUT=xml:output.xml ctest -j $(nproc)
      - name: upload xml
        uses: actions/upload-artifact@v2
        with:
          name: ubuntu-gcc-x64.xml
          path: build/test/output.xml
  test_conformance:
    runs-on: ubuntu-latest
    env:
      CC: gcc
      CXX: g++
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          cmake --preset=ci-unix-ansi
          cmake --build build